#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:5.7
#    container_name: mysql_container
#    environment:
#      MYSQL_ROOT_PASSWORD:
#      MYSQL_DATABASE: livraria
#    ports:
#      - "3307:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#  php:
#    image: php:7.4-cli
#    container_name: php_container
#    depends_on:
#      - mysql
#    volumes:
#      - ./src:/var/www/html
#
#volumes:
#  mysql_data:

version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: livraria
      MYSQL_USER: user
      MYSQL_PASSWORD: 123123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: php:7.4-apache
    container_name: php_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

volumes:
  db_data:
